# Generated by Django 4.0 on 2022-02-06 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 14, 7, 33, 920371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 14, 7, 33, 920371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 14, 7, 33, 921391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
    ]
