# Generated by Django 4.0 on 2022-02-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='email')),
                ('name', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(error_messages={'required': 'Thiếu vai trò'}, max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
